name: anki
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.17.0
  flutter_shaders: ^0.1.0
  flutter_joystick: ^0.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  open_simplex_noise: ^2.3.1
  isolated_worker: ^0.1.1
  performance: ^0.1.1
  provider: ^6.0.5
  open_simplex_2: ^0.2.1
  fast_noise: ^2.0.0
  collection: ^1.15.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.20.0

flutter:
  uses-material-design: true
  assets:
    - assets/spritesheet.png
  shaders:
    - shaders/water.frag
    - shaders/regtanglewater.frag
    - shaders/clouds.frag
