// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaTqFoBCt1Rv7enoSoYf6IywjI-0_lXB4',
    appId: '1:378812942192:web:c2c0d3a6954204ca4871b5',
    messagingSenderId: '378812942192',
    projectId: 'isometric-game-310f1',
    authDomain: 'isometric-game-310f1.firebaseapp.com',
    databaseURL: 'https://isometric-game-310f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isometric-game-310f1.appspot.com',
    measurementId: 'G-17BR3RDF8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLpo8tjPIjntEnIm8jq5VeuQ6vX9p5cWM',
    appId: '1:378812942192:android:21cef200887dd33d4871b5',
    messagingSenderId: '378812942192',
    projectId: 'isometric-game-310f1',
    databaseURL: 'https://isometric-game-310f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isometric-game-310f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj4e3LHOg2SFaV37Gm0deBqBiNtXH90sc',
    appId: '1:378812942192:ios:92205b2acb7fd4e04871b5',
    messagingSenderId: '378812942192',
    projectId: 'isometric-game-310f1',
    databaseURL: 'https://isometric-game-310f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isometric-game-310f1.appspot.com',
    iosBundleId: 'com.example.anki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj4e3LHOg2SFaV37Gm0deBqBiNtXH90sc',
    appId: '1:378812942192:ios:92205b2acb7fd4e04871b5',
    messagingSenderId: '378812942192',
    projectId: 'isometric-game-310f1',
    databaseURL: 'https://isometric-game-310f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isometric-game-310f1.appspot.com',
    iosBundleId: 'com.example.anki',
  );
}
