{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float iTime;\nuniform vec2 iResolution;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvec2 FLT_flutter_local_rand(vec2 co)\n{\n    return fract(sin(vec2(dot(co, vec2(12.98980045318603515625, 78.233001708984375)), dot(co, vec2(63.93399810791015625, 31.4200000762939453125)))) * vec2(43758.546875, 22578.146484375));\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / vec2(1000.0, 500.0);\n    uv = (uv * 2.0) - vec2(1.0);\n    mat2 isoTransform = mat2(vec2(0.707106769084930419921875), vec2(-0.707106769084930419921875, 0.707106769084930419921875));\n    uv = isoTransform * uv;\n    vec2 tileSize = vec2(0.00999999977648258209228515625);\n    vec2 gridPos = floor(uv / tileSize);\n    float diff = 1.03999996185302734375;\n    vec4 colorA = vec4((7.0 * diff) / 255.0, (95.0 * diff) / 255.0, (187.0 * diff) / 255.0, (220.0 * diff) / 255.0);\n    vec4 colorB = vec4(0.02745098061859607696533203125, 0.3725490272045135498046875, 0.7333333492279052734375, 0.862745106220245361328125);\n    vec2 param = gridPos;\n    vec2 r = FLT_flutter_local_rand(param);\n    float t = 1.0 + sin((iTime * (0.5 + r.x)) + r.y);\n    fragColor = mix(colorB, colorA, vec4(t));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 2,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "iTime",
      "rows": 1,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 1,
      "name": "iResolution",
      "rows": 2,
      "type": 10
    }
  ]
}